### PR TITLE
Support multiple keys, multiple attachments

### PR DESCRIPTION
**Pull request by ursm**
This PR includes following two features:
1. More than one attachment is given to one attachment key
2. More than one attachment key is given to one model

### CODE REVIEW

**Comment by sol1dus** [comment]
looks good to me. @abuiles thoughts ?

**Comment by abuiles** [comment]
Thanks!

**Comment by abuiles** [comment]
@ursm maybe could you please update the readme to reflect this? Also I just release 0.3.0 :)

**Comment by sol1dus** [comment]
@abuiles @ursm I'll update

**Comment by ursm** [comment]
@abuiles @sol1dus Thank you so much!

**Pull request merged**
